CREATE TABLE [dbo].[DimDate] (

	[DateKey] date NULL, 
	[Day] int NULL, 
	[DaySuffix] varchar(8000) NULL, 
	[DayName] varchar(8000) NULL, 
	[DayOfWeek] int NULL, 
	[DayOfWeekInMonth] int NULL, 
	[DayOfYear] int NULL, 
	[IsWeekend] int NULL, 
	[Week] int NULL, 
	[ISOweek] int NULL, 
	[FirstOfWeek] date NULL, 
	[LastOfWeek] date NULL, 
	[WeekOfMonth] int NULL, 
	[Month] int NULL, 
	[MonthName] varchar(8000) NULL, 
	[FirstOfMonth] date NULL, 
	[LastOfMonth] date NULL, 
	[FirstOfNextMonth] date NULL, 
	[LastOfNextMonth] date NULL, 
	[Quarter] int NULL, 
	[FirstOfQuarter] date NULL, 
	[LastOfQuarter] date NULL, 
	[Year] int NULL, 
	[ISOYear] int NULL, 
	[FirstOfYear] date NULL, 
	[LastOfYear] date NULL, 
	[IsLeapYear] int NULL, 
	[Has53Weeks] int NULL, 
	[Has53ISOWeeks] int NULL, 
	[YYYYMMDDKey] int NULL
);